server:
  port: 7788
spring:
  application:
    name: coupon-template-serv
  datasource:
#    数据库还没搞
#    Nacos只支持mysql，我就说怎么不上Nacos。乌鱼子
    jdbc-url: jdbc:mysql://127.0.0.1:3306/springc_study?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接池参数配置，比如池子大小、超时时间、是否自动提交等等
    hikari:
      pool-name: GeekbangCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
#      防止ddl结构被自动执行，破坏生产数据
      ddl-auto: none
#      日志打印经过格式化得sql
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false